# Generated by Django 4.2.7 on 2024-05-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_student_cls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='place',
            field=models.CharField(max_length=100, verbose_name='student Place'),
        ),
    ]
